### ISSUE TITLE
好像无法build

### ISSUE THREAD

**Issue by lmuiotctf** [bravehot/db-translate-code#1]
![image](https://github.com/bravehot/tutu-code/assets/52068443/23437285-4b42-41e5-a650-9f316f062752)
build会报错

**Comment by bravehot** [comment]
window 系统下可能会有这个问题，可以看下这个 [issue](https://github.com/vercel/next.js/issues/48603)，或者将  Next 升级到 13.3.4 试下。
我本地 pnpm: 8.4.0, node: 16.8.1, macOS 13.1 没发现这个问题

**Comment by lmuiotctf** [comment]
我在Linux下可以了。然后这个请求接口：api.openai.com，要哪边进行改，我代码搜索了下，好像没找到

**Comment by bravehot** [comment]
这个接口是 `openai` 这个包调用的，代码位置在`src/utils/completion.ts`，因为需要访问 OpenAI，所以调用之前得确保能正常的访问 chatgpt 😝😝

**Comment by lmuiotctf** [comment]
看了下是sdk，可以修改成url形式的嘛，毕竟需要进行翻墙，如果URL，就可以用反代URL

**Comment by bravehot** [comment]
可以的，官方有 [API 文档](https://platform.openai.com/docs/api-reference/introduction)

**Comment by lmuiotctf** [comment]
好的，期待下次迭代

**Comment by lmuiotctf** [comment]
还有就是好像我build 之后，在服务器start运行，修改了代码好像都没用，start还是原始项目

**Comment by bravehot** [comment]
可能有缓存，添加了 Dockerfile 现已支持 Docker 部署
